### ISSUE TITLE
Jacobian in Joint Controller 

### ISSUE THREAD

**Issue by RajPShinde** [bostoncleek/quadruped_control#3]
Hello, why aren't we multiplying the Jacobian.t() with the first two terms to provide the torque?
https://github.com/bostoncleek/quadruped_control/blob/2964bd2001393e638a1ea99665a1115e884e8d7f/quadruped_controller/src/quadruped_controller/joint_controller.cpp#L33

**Comment by bostoncleek** [comment]
Hey, The reason being this is for swing leg control only. The stance legs use the Jacobian transpose [here](https://github.com/bostoncleek/quadruped_control/blob/master/quadruped_controller/src/quadruped_controller/kinematics.cpp#L226).
